from PIL import Image

image = Image.open("example.jpg")
rotated_image = image.rotate(45)
image = Image.open("lenna.jpg")
rgb_image = image.convert("RGB")
image = Image.open("monro.jpg")
red, green, blue = image.split()
new_image = Image.merge("RGB", (red, green, blue))
image = Image.open("red-1.jpg")
coordinates = (100, 0, 696, 522)
cropped = image.crop(coordinates)
image = Image.open("red-1.jpg")
coordinates = (50, 0, 646, 522)
cropped = image.crop(coordinates)
image1 = Image.open("red-2.jpg")
image2 = Image.open("red-3.jpg")
image3 = Image.blend(image1, image2, 0.5)
image = Image.open("blue-1.jpg")
coordinates = (0, 0, 596, 522)
cropped = image.crop(coordinates)
image = Image.open("blue-1.jpg")
coordinates = (50, 0, 646, 522)
cropped = image.crop(coordinates)
image1 = Image.open("blue-2.jpg")
image2 = Image.open("blue-3.jpg")
image3 = Image.blend(image1, image2, 0.5)
image = Image.open("green-1.jpg")
coordinates = (50, 0, 646, 522)
cropped = image.crop(coordinates)
image1 = Image.open("red-4.jpg")
image2 = Image.open("green-2.jpg")
image3 = Image.open('blue-4.jpg')
new_image = Image.merge("RGB", (image1, image2, image3))
new_image.save("monro_2.jpg")
image = Image.open("monro_2.jpg")
image.thumbnail((80, 70))
image.save("monro_3.jpg")
